### ISSUE TITLE
Set fixed position for right column

### ISSUE THREAD

**Issue by dluksza** [ryanhellyer/hellish-simplicity#10]
Right column space is wasted when posts are longer then column height. Making this column fixed will make this space always occupied.

Right column should have fixed position, it should scroll down as long as there is content within it. When content ends is should also not be scrolled, only main post content should scroll then.

**Comment by ryanhellyer** [comment]
There is a big list of downsides to go along with that too.

If I were going to go to a fixed position sidebar, I'd probably move it to the left hand side since it would be weird to scroll a scroll bar on the right hand side, but only the left hand content would move.

**Comment by ryanhellyer** [comment]
I'm going to list this as "wontfix" sorry, as it's not something I'm likely to do, although I do understand your reasons for suggesting it.
