### ISSUE TITLE
Add rich text snippets

### ISSUE THREAD

**Issue by ryanhellyer** [ryanhellyer/hellish-simplicity#9]
Idea courtesy of Henrik.

Google Web Master tools doesn't like the lack of rich text snippets, see Google Web Master Tools > Search Appearance > Structured data

**Comment by ryanhellyer** [comment]
I've added "updated" to the <time> tag, but Google Webmaster tools is also asking for the author to be listed on pages, which seems somewhat odd to me since this seems somewhat silly on many websites. My blog for example has no reason for displaying the post/page authors, since the entire blog is clearly written by me and no one else.

Any ideas on how to handle this situation?

**Comment by kasparsd** [comment]
```
.page .author {
    display:none;
}
```

or maybe Microformats allow for item values in element attributes (`title`)?

**Comment by ryanhellyer** [comment]
That was my first though, but Google recommends not hiding rich text snippets :/

**Comment by ryanhellyer** [comment]
Putting it in an attribute would be okay. It's still a bit weird since it's often obvious who the page author but at least it's not visible on page until you hover something.

**Comment by ryanhellyer** [comment]
I received an email saying that this problem has gone away automatically. Perhaps it was a bug in Google.
